spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rezero
    username: rezero_user
    password: reZero1234
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    session:
      timeout: 30m